name: Run Tests

# Uruchamiaj workflow przy pushu i pull requestach
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Sprawdzenie repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ustawienie środowiska Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Instalacja zależności
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Uruchomienie testów
      - name: Run tests
        run: pytest tests/